/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/public/{subdomain}/hotel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados públicos do hotel (cabeçalho da página de reservas) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example aurora */
                    subdomain: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nome, subdomínio e % de sinal */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reservas online desativadas */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Hotel não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/{subdomain}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Categorias disponíveis no período, com preço da estadia */
        get: {
            parameters: {
                query: {
                    /** @example 2026-10-10 */
                    check_in: string;
                    /** @example 2026-10-13 */
                    check_out: string;
                    /** @example 2 */
                    guests?: number;
                };
                header?: never;
                path: {
                    /** @example aurora */
                    subdomain: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de categorias disponíveis + preço */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Datas inválidas */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Hotel não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/{subdomain}/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria reserva online e gera cobrança PIX do sinal */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example aurora */
                    subdomain: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        category_id: string;
                        /**
                         * Format: date
                         * @example 2026-10-10
                         */
                        check_in: string;
                        /**
                         * Format: date
                         * @example 2026-10-13
                         */
                        check_out: string;
                        /** @example 2 */
                        guests?: number;
                        guest: {
                            /** @example Maria Oliveira */
                            full_name: string;
                            /** @example maria@example.com */
                            email?: string;
                            /** @example (11) 99999-9999 */
                            phone?: string;
                            /** @example 123.456.789-00 */
                            cpf?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Reserva PENDING criada + QR PIX do sinal */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Campos obrigatórios ausentes ou datas inválidas */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Hotel ou categoria não encontrados */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Sem disponibilidade na categoria para o período */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Categoria não comporta os hóspedes ou sem preço */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/{subdomain}/bookings/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status da reserva (polling pós-pagamento PIX) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example aurora */
                    subdomain: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status da reserva e do sinal */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reserva não encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/pix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmação de pagamento PIX (callback do PSP)
         * @description Marca o pagamento como PAID e promove a reserva PENDING→CONFIRMED. Idempotente. No provider simulado, dispare manualmente com o provider_charge_id retornado na criação da reserva.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example fake_a6ada2c2-eaea-4ff6-ba41-1919b87688f3 */
                        provider_charge_id: string;
                    };
                };
            };
            responses: {
                /** @description Pagamento confirmado (ou já processado) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description provider_charge_id ausente */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cobrança não encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra novo tenant e usuário ADMIN */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Hotel Paraíso */
                        tenantName: string;
                        /** @example João Admin */
                        name: string;
                        /** @example admin@paraiso.com */
                        email: string;
                        /** @example senha123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Tenant e usuário criados */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Dados inválidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description E-mail já cadastrado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica usuário e retorna JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example admin@paraiso.com */
                        email: string;
                        /** @example senha123 */
                        password: string;
                        /**
                         * @description Subdomain do hotel (opcional). Recomendado em ambientes multi-tenant para evitar colisão de e-mails entre hotéis.
                         * @example hotel-paraiso
                         */
                        subdomain?: string;
                    };
                };
            };
            responses: {
                /** @description JWT gerado com sucesso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Campos obrigatórios ausentes */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Credenciais inválidas ou subdomain não encontrado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description E-mail existe em múltiplos hotéis — informe o subdomain para desambiguar */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica usuário e retorna JWT (alias de /auth/login) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example admin@paraiso.com */
                        email: string;
                        /** @example senha123 */
                        password: string;
                        /** @example hotel-paraiso */
                        subdomain?: string;
                    };
                };
            };
            responses: {
                /** @description JWT gerado com sucesso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Credenciais inválidas */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna a configuração do próprio hotel */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dados e config do hotel (booking_enabled, deposit_percent) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Sem token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Atualiza a config do hotel (ADMIN) — liga/desliga reservas online e ajusta o sinal */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Hotel Aurora */
                        name?: string;
                        /** @example 12.345.678/0001-90 */
                        legal_id?: string;
                        /**
                         * @description Liga/desliga a página pública de reservas diretas
                         * @example true
                         */
                        booking_enabled?: boolean;
                        /**
                         * @description Percentual do sinal PIX cobrado na reserva online (0–100)
                         * @example 30
                         */
                        deposit_percent?: number;
                    };
                };
            };
            responses: {
                /** @description Config atualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Valor inválido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Apenas ADMIN */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista usuários do tenant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de usuários */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Cria novo usuário */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            responses: {
                /** @description Usuário criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Busca usuário por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usuário encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Atualiza usuário */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Atualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Remove usuário */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removido */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/room-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista categorias */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Cria categoria */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RoomCategory"];
                };
            };
            responses: {
                /** @description Criada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/room-categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Busca por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Atualiza */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Remove */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista quartos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Cria quarto */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Room"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista quartos disponíveis em um período */
        get: {
            parameters: {
                query: {
                    /** @description Data de entrada (YYYY-MM-DD) */
                    check_in: string;
                    /** @description Data de saída (YYYY-MM-DD) */
                    check_out: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de quartos sem conflito no período */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description check_in e check_out são obrigatórios ou check_in >= check_out */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Busca por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Atualiza */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Remove */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista hóspedes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Cria hóspede */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Guest"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Busca por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Atualiza */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Remove */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista reservas (filtro por período e paginação opcionais) */
        get: {
            parameters: {
                query?: {
                    /** @description Início do intervalo (YYYY-MM-DD). Devolve reservas que se sobrepõem ao período. */
                    from?: string;
                    /** @description Fim do intervalo (YYYY-MM-DD). */
                    to?: string;
                    /** @description Página (1+). Presente page ou limit, a resposta vira { data, total, page, limit }. */
                    page?: number;
                    /** @description Itens por página (máx. 100). */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK — array puro sem paginação, ou { data, total, page, limit } quando page/limit presentes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Cria reserva (vincula quarto principal na tabela pivô reservation_rooms) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
            responses: {
                /** @description Criada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Busca por ID (inclui quartos N:N) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Atualiza reserva */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Remove reserva (ADMIN) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Cancela reserva (apenas PENDING ou CONFIRMED) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reserva cancelada — status alterado para CANCELLED */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reserva não encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reserva não pode ser cancelada no status atual (CHECKED_IN, CHECKED_OUT ou já CANCELLED) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Realiza check-in */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status alterado para CHECKED_IN */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/check-out": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Realiza check-out */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status alterado para CHECKED_OUT */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/bill": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Fechamento de conta: (diária + consumos) − pagamentos confirmados */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Conta com room_total, consumptions_total, grand_total, total_paid, balance_due */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reserva não encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/consumptions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Lista consumos extras da reserva */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de consumos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Lança consumo extra (frigobar, restaurante, spa) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example Frigobar */
                        description: string;
                        /** @example 50 */
                        amount: number;
                        /** Format: date-time */
                        consumed_at?: string;
                    };
                };
            };
            responses: {
                /** @description Consumo lançado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Dados inválidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Reserva não encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/consumptions/{consumptionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                consumptionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove consumo extra (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    consumptionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removido */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adiciona quarto à reserva (tabela pivô reservation_rooms) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        room_id?: string;
                    };
                };
            };
            responses: {
                /** @description Quarto vinculado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Já vinculado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/rooms/{roomId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                roomId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove quarto da reserva (tabela pivô) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Desvinculado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista pagamentos do tenant */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Registra novo pagamento */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        reservation_id: string;
                        /** @example 300 */
                        amount: number;
                        /**
                         * @example PIX
                         * @enum {string}
                         */
                        method: "PIX" | "CARTAO_CREDITO" | "CARTAO_DEBITO" | "DINHEIRO";
                        /** Format: date-time */
                        paid_at?: string;
                    };
                };
            };
            responses: {
                /** @description Pagamento registrado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Busca pagamento por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Atualiza pagamento */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Remove pagamento */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/revenue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Caixa realizado vs esperado vs inadimplência
         * @description Retorna receita realizada (pagamentos recebidos) agrupada por mês, receita esperada (reservas ativas sem pagamento completo) e lista de inadimplentes. Filtro por período opcional.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Data inicial do filtro (YYYY-MM-DD) */
                    start?: string;
                    /** @description Data final do filtro (YYYY-MM-DD) */
                    end?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resumo financeiro do tenant */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            realized?: {
                                /** @example 18500 */
                                total?: number;
                                by_month?: {
                                    /** @example 2026-01 */
                                    month?: string;
                                    /** @example 4200 */
                                    total?: number;
                                }[];
                            };
                            expected?: {
                                /** @example 6200 */
                                total?: number;
                            };
                            unpaid?: {
                                /** Format: uuid */
                                reservation_id?: string;
                                /** @example Maria Oliveira */
                                guest?: string;
                                /** @example 600 */
                                amount?: number;
                                /** Format: date */
                                check_in_date?: string;
                                /** Format: date */
                                check_out_date?: string;
                            }[];
                        };
                    };
                };
                /** @description Token não fornecido ou inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/occupancy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxa de ocupação + ADR + RevPAR
         * @description Retorna contagem de quartos por status, taxa de ocupação percentual, ADR (diária média) e RevPAR (receita por quarto disponível) para a data informada.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Data de referência (YYYY-MM-DD). Default: hoje. */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Indicadores de ocupação do dia */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: date
                             * @example 2026-06-27
                             */
                            date?: string;
                            /** @example 15 */
                            total_rooms?: number;
                            /** @example 9 */
                            occupied?: number;
                            /** @example 4 */
                            available?: number;
                            /** @example 2 */
                            cleaning?: number;
                            /**
                             * @description Percentual de ocupação (0–100)
                             * @example 60
                             */
                            occupancy_rate?: number;
                            /**
                             * @description Average Daily Rate — diária média dos quartos vendidos
                             * @example 312.5
                             */
                            adr?: number;
                            /**
                             * @description Revenue Per Available Room — ADR × occupancy_rate / 100
                             * @example 187.5
                             */
                            revpar?: number;
                        };
                    };
                };
                /** @description Token não fornecido ou inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alertas operacionais do dia
         * @description Retorna três listas de atenção imediata: risco de no-show (CONFIRMED sem pagamento com check-in hoje), quartos em limpeza há tempo e reservas PENDING há mais de 48h.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alertas agrupados por categoria */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Reservas confirmadas para hoje sem pagamento */
                            no_show_risk?: {
                                /** Format: uuid */
                                reservation_id?: string;
                                /** @example João Silva */
                                guest?: string;
                                /** @example (11) 99999-9999 */
                                guest_phone?: string;
                                /** Format: date */
                                check_in_date?: string;
                                /** @example 450 */
                                amount?: number;
                            }[];
                            /** @description Quartos com status CLEANING */
                            cleaning_pending?: {
                                /** Format: uuid */
                                room_id?: string;
                                /** @example 204 */
                                room_number?: string;
                                /** @example Standard */
                                category?: string;
                                /** Format: date-time */
                                cleaning_since?: string;
                            }[];
                            /** @description Reservas PENDING criadas há mais de 48h */
                            pending_too_long?: {
                                /** Format: uuid */
                                reservation_id?: string;
                                /** @example Ana Costa */
                                guest?: string;
                                /** Format: date */
                                check_in_date?: string;
                                /** @example 300 */
                                amount?: number;
                                /** @example 72.5 */
                                hours_pending?: number;
                            }[];
                        };
                    };
                };
                /** @description Token não fornecido ou inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/seasonality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Histórico mensal de reservas e receita
         * @description Retorna dados agrupados por mês para identificar sazonalidade: número de reservas, receita total e média de noites por reserva.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Quantos meses de histórico retornar (1–60). Default: 12. */
                    months?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array de meses com indicadores */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 2026-01 */
                            month?: string;
                            /** @example 8 */
                            reservations?: number;
                            /** @example 5200 */
                            revenue?: number;
                            /** @example 3.2 */
                            avg_nights?: number;
                        }[];
                    };
                };
                /** @description months fora do intervalo permitido (1–60) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Token não fornecido ou inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/revenue-by-category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Receita e rentabilidade por categoria de quarto
         * @description Ranqueia as categorias de quarto por receita gerada, mostrando número de reservas e ticket médio por categoria.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Data inicial (YYYY-MM-DD) */
                    start?: string;
                    /** @description Data final (YYYY-MM-DD) */
                    end?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ranking de categorias por receita */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Suite Presidencial */
                            category?: string;
                            /** @example 2 */
                            reservations?: number;
                            /** @example 5600 */
                            revenue?: number;
                            /** @example 2800 */
                            avg_ticket?: number;
                        }[];
                    };
                };
                /** @description Token não fornecido ou inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/payment-mix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mix de meios de pagamento com percentual
         * @description Agrupa pagamentos por método (PIX, CARTAO_CREDITO, CARTAO_DEBITO, DINHEIRO) com total em reais e percentual sobre o total do período.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Data inicial (YYYY-MM-DD) */
                    start?: string;
                    /** @description Data final (YYYY-MM-DD) */
                    end?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mix de pagamentos ordenado por total */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example PIX */
                            method?: string;
                            /** @example 9 */
                            count?: number;
                            /** @example 11200 */
                            total?: number;
                            /**
                             * @description Percentual sobre o total do período
                             * @example 60.54
                             */
                            pct?: number;
                        }[];
                    };
                };
                /** @description Token não fornecido ou inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/top-guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hóspedes mais valiosos por lifetime value
         * @description Ranqueia hóspedes pela soma histórica de reservas não canceladas, mostrando número de estadias, valor acumulado e data da última visita.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Quantidade de hóspedes a retornar (1–100). Default: 10. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ranking de hóspedes por lifetime value */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            guest_id?: string;
                            /** @example Carlos Eduardo */
                            full_name?: string;
                            /** Format: email */
                            email?: string;
                            /** @example 3 */
                            total_reservations?: number;
                            /** @example 4200 */
                            lifetime_value?: number;
                            /**
                             * Format: date
                             * @example 2026-06-20
                             */
                            last_stay?: string;
                        }[];
                    };
                };
                /** @description limit fora do intervalo permitido (1–100) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Token não fornecido ou inválido */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Erro interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Tenant: {
            /** Format: uuid */
            id?: string;
            /** @example Hotel Paraíso */
            name?: string;
            /** @example paraiso */
            subdomain?: string;
            /** @example 12.345.678/0001-90 */
            legal_id?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED";
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenant_id?: string;
            /** @example João Silva */
            name?: string;
            /** Format: email */
            email?: string;
            /** @enum {string} */
            role?: "ADMIN" | "RECEPTIONIST";
        };
        RoomCategory: {
            /** Format: uuid */
            id?: string;
            /** @example Standard */
            name?: string;
            /** @example 2 */
            capacity?: number;
            /**
             * Format: float
             * @example 150
             */
            price_per_night?: number;
        };
        Room: {
            /** Format: uuid */
            id?: string;
            /** @example 101 */
            number?: string;
            /** @example 1 */
            floor?: number;
            /** @enum {string} */
            status?: "AVAILABLE" | "OCCUPIED" | "MAINTENANCE" | "CLEANING";
            /** Format: uuid */
            category_id?: string;
        };
        Guest: {
            /** Format: uuid */
            id?: string;
            /** @example Maria Oliveira */
            full_name?: string;
            /** @example 123.456.789-00 */
            cpf?: string;
            /** @example (11) 99999-9999 */
            phone?: string;
            /** Format: email */
            email?: string;
        };
        Reservation: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            guest_id?: string;
            /** Format: uuid */
            room_id?: string;
            /** Format: uuid */
            user_id?: string;
            /**
             * Format: date
             * @example 2026-07-01
             */
            check_in_date?: string;
            /**
             * Format: date
             * @example 2026-07-05
             */
            check_out_date?: string;
            /** @enum {string} */
            status?: "PENDING" | "CONFIRMED" | "CHECKED_IN" | "CHECKED_OUT" | "CANCELLED";
            /**
             * Format: float
             * @example 600
             */
            total_amount?: number;
        };
        Error: {
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
